_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "6": 4.50.1
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-x86_64
